{{- range $appName, $appConfig := .Values.apps }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "hello-world.fullname" $) $appName }}
  labels:
    app.kubernetes.io/component: {{ $appName }}
    {{- include "hello-world.labels" $ | nindent 4 }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ $appName }}
      {{- include "hello-world.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ $appName }}
        {{- include "hello-world.selectorLabels" $ | nindent 8 }}
    spec:
      containers:
        - name: {{ $.Chart.Name }}
          image: {{ $.Values.image.repository }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: nginx-index-file
              mountPath: /usr/share/nginx/html/
      volumes:
        - name: nginx-index-file
          configMap:
            name: {{ include "hello-world.fullname" $ }}-{{ $appName }}
{{- end }}