{{- range $appName, $appConfig := .Values.apps }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" (include "hello-world.fullname" $) $appName }}
  labels:
    {{- include "hello-world.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $appName }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: {{ $appName }}
{{- end }}